### PR TITLE
- added 501(c)3 designation

### PR DESCRIPTION
**Pull request by grantdobbe**

### CODE REVIEW

**Comment by clairegriffin** [comment]
We aren't actually incorporated in California but the official mailing address is in state.  I'm not sure how "based in California" is meant to be interpreted in this context.

**Comment by grantdobbe** [comment]
We could drop the "based in California" part to clarify it.

**Comment by clairegriffin** [comment]
Okay, lets drop the 'based in' since it is ambiguous.  It isn't really necessary.

**Review by clairegriffin — APPROVED** [review]
Looks good.

**Pull request merged**
